
export const ACTIVE_SURVEYS_BEGIN = 'ACTIVE SURVEYS_BEGIN';
export const ACTIVE_SURVEYS_SUCCESS = 'ACTIVE SURVEYS_SUCCESS';
export const ACTIVE_SURVEYS_FAILURE = 'ACTIVE SURVEYS_FAILURE';

export const CAREGROUP_BEGIN = 'CAREGROUP_BEGIN';
export const CAREGROUP_SUCCESS = 'CAREGROUP_SUCCESS';
export const CAREGROUP_FAILURE = 'CAREGROUP_FAILURE';

export const CAREGROUP_SAVE_BEGIN = 'CAREGROUP_SAVE_BEGIN';
export const CAREGROUP_SAVE_SUCCESS = 'CAREGROUP_SAVE_SUCCESS';
export const CAREGROUP_SAVE_FAILURE = 'CAREGROUP_SAVE_FAILURE';
export const CAREGROUP_SAVE_RESET = 'CAREGROUP_RESET';

export const CAREGROUP_UPDATE_SAVE_BEGIN = 'CAREGROUP_UPDATE_SAVE_BEGIN';
export const CAREGROUP_UPDATE_SAVE_SUCCESS = 'CAREGROUP_UPDATE_SAVE_SUCCESS';
export const CAREGROUP_UPDATE_SAVE_FAILURE = 'CAREGROUP_UPDATE_SAVE_FAILURE';
export const CAREGROUP_UPDATE_SAVE_RESET = 'CAREGROUP_UPDATE_RESET';

export const CONSOLE_TITLE = 'CONSOLE_TITLE';

export const EPISODE_STATUS_UPDATE_BEGIN = "EPISODE_STATUS_UPDATE_BEGIN";
export const EPISODE_STATUS_UPDATE_SUCCESS = "EPISODE_STATUS_SUCCESS";
export const EPISODE_STATUS_UPDATE_FAILURE = "EPISODE_STATUS_UPDATE_FAILURE";
export const EPISODE_STATUS_UPDATE_RESET = "EPISODE_STATUS_UPDATE_RESET";

export const PATIENT_BEGIN = 'PATIENT_BEGIN';
export const PATIENT_SUCCESS = 'PATIENT_SUCCESS';
export const PATIENT_FAILURE = 'PATIENT_FAILURE';
export const PATIENT_RESET = 'PATIENT_RESET';

export const PATIENT_SAVE_BEGIN = 'PATIENT_SAVE_BEGIN';
export const PATIENT_SAVE_SUCCESS = 'PATIENT_SAVE_SUCCESS';
export const PATIENT_SAVE_FAILURE = 'PATIENT_SAVE_FAILURE';
export const PATIENT_SAVE_RESET = 'PATIENT_SAVE_RESET';

export const PATIENTS_BY_CAREGROUP_BEGIN = 'LIST_PATIENTS_BY_CAREGROUP_BEGIN';
export const PATIENTS_BY_CAREGROUP_SUCCESS = 'LIST_PATIENTS_BY_CAREGROUP_SUCCESS';
export const PATIENTS_BY_CAREGROUP_FAILURE = 'LIST_PATIENTS_BY_CAREGROUP_FAILURE';

export const PATIENTS_BY_PROVIDER_BEGIN = 'LIST_PATIENTS_BY_PROVIDER_BEGIN';
export const PATIENTS_BY_PROVIDER_SUCCESS = 'LIST_PATIENTS_BY_PROVIDER_SUCCESS';
export const PATIENTS_BY_PROVIDER_FAILURE = 'LIST_PATIENTS_BY_PROVIDER_FAILURE';

export const PATIENT_UPDATE_SAVE_BEGIN = 'PATIENT_UPDATE_SAVE_BEGIN';
export const PATIENT_UPDATE_SAVE_SUCCESS = 'PATIENT_UPDATE_SAVE_SUCCESS';
export const PATIENT_UPDATE_SAVE_FAILURE= 'PATIENT_UPDATE_SAVE_FAILURE';
export const PATIENT_UPDATE_SAVE_RESET= 'PATIENT_UPDATE_SAVE_RESET';

export const PROVIDER_BEGIN = 'PROVIDER_BEGIN';
export const PROVIDER_SUCCESS = 'PROVIDER_SUCCESS';
export const PROVIDER_FAILURE = 'PROVIDER_FAILURE';

export const PROVIDER_SAVE_BEGIN = 'PROVIDER_SAVE_BEGIN';
export const PROVIDER_SAVE_SUCCESS = 'PROVIDER_SAVE_SUCCESS';
export const PROVIDER_SAVE_FAILURE = 'PROVIDER_SAVE_FAILURE';
export const PROVIDER_SAVE_RESET = 'PROVIDER_SAVE_RESET';

export const PROVIDER_EMAIL_BEGIN = 'PROVIDER_EMAIL_BEGIN';
export const PROVIDER_EMAIL_SUCCESS = 'PROVIDER_EMAIL_SUCCESS';
export const PROVIDER_EMAIL_FAILURE = 'PROVIDER_EMAIL_FAILURE';
export const PROVIDER_EMAIL_RESET = 'PROVIDER_EMAIL_RESET';

export const PROVIDER_UPDATE_SAVE_BEGIN = 'PROVIDER_UPDATE_SAVE_BEGIN';
export const PROVIDER_UPDATE_SAVE_SUCCESS = 'PROVIDER_UPDATE_SAVE_SUCCESS';
export const PROVIDER_UPDATE_SAVE_FAILURE = 'PROVIDER_UPDATE_SAVE_FAILURE';
export const PROVIDER_UPDATE_SAVE_RESET = 'PROVIDER_UPDATE_SAVE_RESET';

export const SURVEY_BEGIN = 'SURVEY_BEGIN';
export const SURVEY_SUCCESS = 'SURVEY_SUCCESS';
export const SURVEY_FAILURE = 'SURVEY_FAILURE';
export const SURVEY_RESET = 'SURVEY_RESET';

export const QUESTIONS_BEGIN = 'QUESTIONS_BEGIN'
export const QUESTIONS_SUCCESS = 'QUESTIONS_SUCCESS'
export const QUESTIONS_FAILURE = 'QUESTIONS_FAILURE'

export const USER_PROFILE = 'USER_PROFILE';
export const USER_FAILURE = 'USER_FAILURE';