// export const EMAIL_CHANGED = 'EMAIL_CHANGED';
// export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const ACTIVE_SURVEYS_BEGIN = 'ACTIVE SURVEYS_BEGIN';
export const ACTIVE_SURVEYS_SUCCESS = 'ACTIVE SURVEYS_SUCCESS';
export const ACTIVE_SURVEYS_FAILURE = 'ACTIVE SURVEYS_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_AUTHENTICATED = 'LOGIN_AUTHENTICATED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CAREGROUP_BEGIN = 'CAREGROUP_BEGIN';
export const CAREGROUP_SUCCESS = 'CAREGROUP_SUCCESS';
export const CAREGROUP_FAILURE = 'CAREGROUP_FAILURE';

export const CONSOLE_TITLE = 'CONSOLE_TITLE';

export const PATIENT_BEGIN = 'PATIENT_BEGIN';
export const PATIENT_SUCCESS = 'PATIENT_SUCCESS';
export const PATIENT_FAILURE = 'PATIENT_FAILURE';

export const PATIENTS_BY_CAREGROUP_BEGIN = 'LIST_PATIENTS_BY_CAREGROUP_BEGIN';
export const PATIENTS_BY_CAREGROUP_SUCCESS = 'LIST_PATIENTS_BY_CAREGROUP_SUCCESS';
export const PATIENTS_BY_CAREGROUP_FAILURE = 'LIST_PATIENTS_BY_CAREGROUP_FAILURE';

export const PATIENTS_BY_PROVIDER_BEGIN = 'LIST_PATIENTS_BY_PROVIDER_BEGIN';
export const PATIENTS_BY_PROVIDER_SUCCESS = 'LIST_PATIENTS_BY_PROVIDER_SUCCESS';
export const PATIENTS_BY_PROVIDER_FAILURE = 'LIST_PATIENTS_BY_PROVIDER_FAILURE';

export const PROVIDER_BEGIN = 'PROVIDER_BEGIN';
export const PROVIDER_SUCCESS = 'PROVIDER_SUCCESS';
export const PROVIDER_FAILURE = 'PROVIDER_FAILURE';

export const QUESTIONS_BEGIN = 'QUESTIONS_BEGIN'
export const QUESTIONS_SUCCESS = 'QUESTIONS_SUCCESS'
export const QUESTIONS_FAILURE = 'QUESTIONS_FAILURE'

export const USER_PROFILE = 'USER_PROFILE';